### ISSUE TITLE
Error 'vimeo.com refused to connect'

### ISSUE THREAD

**Issue by tumispro** [tanjemark/vimeo#1]
Always gives me a 'vimeo.com refused to connect.' error in the preview and origin error in the console:

`Refused to display 'https://vimeo.com/XXX' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

It would also be great if it could optionally only save the video ID and not the full URL, as it's more flexible :)

**Comment by tanjemark** [comment]
I think you have to use the player URL, https://player.vimeo.com/video/xxxxx

Great idea, please submit a Pull Request! 😊
